#!/usr/bin/env node
/**
 * Guards src/data/cities.ts. Runs on prebuild.
 *
 * 1. CITIES key must equal its `slug` and be url-safe. City URLs are built
 *    from the KEY, not the slug field — a `westBoylston` key silently shipped
 *    7 camelCase URLs while the kebab-case form 404'd. This check exists so
 *    that cannot happen again.
 * 2. Census-sourced numbers must be present and sane. The file is generated by
 *    scripts/build-cities.js; a bad merge that drops population or emits a
 *    placeholder should fail the build, not reach a resident's screen.
 * 3. pre1980Percent must be a percentage. It is shown as a fact about the
 *    reader's own town.
 */
const fs = require('fs')
const path = require('path')

const src = fs.readFileSync(path.join(__dirname, '../src/data/cities.ts'), 'utf8')
const body = src.slice(src.indexOf('export const CITIES'))
const errors = []
let count = 0

for (const m of body.matchAll(/^ {2}'([^']+)': \{([\s\S]*?)^ {2}\},/gm)) {
  const key = m[1]
  const block = m[2]
  count++

  const slug = block.match(/slug: '([^']+)'/)?.[1]
  if (slug !== key) errors.push(`${key}: key !== slug ('${slug}') — URLs are built from the key`)
  if (!/^[a-z0-9-]+$/.test(key)) errors.push(`${key}: key is not url-safe lowercase`)

  const pop = Number(block.match(/population: (\d+)/)?.[1])
  const hv = Number(block.match(/medianHomeValue: (\d+)/)?.[1])
  const pre = block.match(/pre1980Percent: (\d+)/)?.[1]

  if (!pop || pop < 100) errors.push(`${key}: implausible population (${pop})`)
  if (!hv || hv < 10000) errors.push(`${key}: implausible medianHomeValue (${hv})`)
  if (pre != null && (Number(pre) < 0 || Number(pre) > 100))
    errors.push(`${key}: pre1980Percent out of range (${pre})`)
}

if (count === 0) errors.push('No cities parsed — the CITIES block shape changed?')

if (errors.length) {
  console.error('✗ cities check failed:\n')
  for (const e of errors) console.error('  - ' + e)
  process.exit(1)
}
console.log(`✓ cities check: ${count} cities, keys match slugs, Census values present`)
